### ISSUE TITLE
TOS

### ISSUE THREAD

**Issue by diVineProportion** [ShadowNoxX/OmegleBot#3]
not sure how you are able to bypass the terms of service agreement in your own code, but..

```
driver.find_element_by_xpath('/html/body/div[7]/div/p[1]/label/input').click()
driver.find_element_by_xpath('/html/body/div[7]/div/p[2]/label/input').click()
driver.find_element_by_xpath('/html/body/div[7]/div/p[3]/input').click()
``` 

#4

**Comment by romainvandooren** [comment]
Hi,
Thank you for opening an issue.
The Omegle website changed since I wrote this code. There wasn't T.O.S agreements at that time.
Thank you for your pull request, I merged it.
